# .github/workflows/deploy.yml
name: Deploy Eyes Docs
on:
  push:
    branches: [master]
    paths: # ä»…ç›‘æ§å­æ¨¡å—ç›®å½•ä¸‹çš„å˜æ›´
      - 'apps/**' 

permissions:
  contents: write # å…è®¸æ¨é€æ„å»ºäº§ç‰©

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code ğŸ›ï¸
        uses: actions/checkout@v4
        with:
          submodules: recursive # å…³é”®ï¼šé€’å½’æ‹‰å–å­æ¨¡å—

      - name: Install pnpm ğŸ”§
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: See pwd â€¢Íˆá´—â€¢Íˆ
        run: |
          echo "å½“å‰å·¥ä½œç›®å½•: $(pwd)"
          ls

      - name: Install Dependencies ğŸ”§
        run: pnpm i

      - name: Build Docs ğŸ”§
        # working-directory: /apps/eyes æŒ‡å®šå­æ¨¡å—è·¯å¾„
        run: pnpm run build:eyes

      - name: Deploy to GH Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: apps/eyes/.vitepress/dist # æŒ‡å‘æ„å»ºäº§ç‰©çš„æœ€ç»ˆè·¯å¾„
          destination_dir: eyes # æŒ‡å®šéƒ¨ç½²åˆ°gh-pagesåˆ†æ”¯çš„/eyesç›®å½•
          keep_files: false  # æ¸…ç†æ—§æ–‡ä»¶
      
      - name: See pwd â€¢Íˆá´—â€¢Íˆ
        run: |
          echo "å½“å‰å·¥ä½œç›®å½•: $(pwd)"
          ls
          
      # 7. æ¸…ç†æ„å»ºäº§ç‰©
      - name: Cleanup Artifacts
        run: rm -rf apps/eyes/.vitepress/dist  # åˆ é™¤æ•´ä¸ªdistç›®å½•